language: objective-c
osx_image: xcode9

script:
  - set -o pipefail
  - xcodebuild clean test -workspace Upsurge.xcworkspace -scheme "Upsurge OSX"
  - xcodebuild clean test -workspace Upsurge.xcworkspace -scheme "Upsurge iOS" -destination 'platform=iOS Simulator,name=iPhone 7'

after_success:
  - bash <(curl -s https://codecov.io/bash)
